# Site settings
title: Webjeda Sharebar Demo
tag_text: Sharebar Demo
description: A responsive, fast loading, only css share bar for Jekyll websites and blogs.
url: "http://webjeda.com"
baseurl: /webjeda-sharebar

# Build settings
markdown: kramdown

exclude: ["README.md"]

#sass: 
#  style: compressed

#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []



# Tracker
analytics: UA-83979019-1

plugins:
    - jekyll-seo-tag